[package]
name = "kovi-plugin-getpic"
version = "0.1.0"
edition = "2021"

[dependencies]
kovi.workspace = true
reqwest = { version = "0.11", features = ["blocking"] }
regex = "1"
getrandom = "0.2"
base64 = "0.22"
